<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Operasional_status extends Admin_controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Operasional_status_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));

        if ($q <> '') {
            $config['base_url'] = base_url() . 'operasional_status/index?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'operasional_status/index?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'operasional_status/index';
            $config['first_url'] = base_url() . 'operasional_status/index';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Operasional_status_model->total_rows($q);
        $config['attributes'] = array('class' => 'page-link');
        $operasional_status = $this->Operasional_status_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'operasional_status_data' => $operasional_status,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->render_view('operasional_status/operasional_status_list', $data);
    }

    public function read($id)
    {
        $row = $this->Operasional_status_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'nama' => $row->nama,
	    );
            $this->render_view('operasional_status/operasional_status_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('operasional_status'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('operasional_status/create_action'),
	    'id' => set_value('id'),
	    'nama' => set_value('nama'),
	);
        $this->render_view('operasional_status/operasional_status_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
	    );

            $this->Operasional_status_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('operasional_status'));
        }
    }

    public function update($id)
    {
        $row = $this->Operasional_status_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('operasional_status/update_action'),
		'id' => set_value('id', $row->id),
		'nama' => set_value('nama', $row->nama),
	    );
            $this->render_view('operasional_status/operasional_status_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('operasional_status'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'nama' => $this->input->post('nama',TRUE),
	    );

            $this->Operasional_status_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('operasional_status'));
        }
    }

    public function delete($id)
    {
        $row = $this->Operasional_status_model->get_by_id($id);

        if ($row) {
            $this->Operasional_status_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('operasional_status'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('operasional_status'));
        }
    }

    public function _rules()
    {
	$this->form_validation->set_rules('nama', 'nama', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Operasional_status.php */
/* Location: ./application/controllers/Operasional_status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-27 05:31:03 */
/* http://harviacode.com */