<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Asal_pemilik_model extends CI_Model
{

    public $table = 'asal_pemilik';
    public $id    = 'id';
    public $order = 'DESC';

    public function __construct()
    {
        parent::__construct();
    }

    // get all
    public function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    public function get_asal()
    {
        $this->db->where('jenis', 1);
        return $this->db->get($this->table)->result();
    }
    public function get_pemilik()
    {
        $this->db->where('jenis', 2);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    public function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    public function total_rows($q = null)
    {
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('sk_brg', $q);
        $this->db->or_like('npwp', $q);
        $this->db->or_like('jenis', $q);
        $this->db->or_like('pph', $q);
        $this->db->or_like('total_pph', $q);
        $this->db->or_like('unix', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('updated_at', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    public function get_limit_data($limit, $start = 0, $q = null)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('sk_brg', $q);
        $this->db->or_like('npwp', $q);
        $this->db->or_like('jenis', $q);
        $this->db->or_like('pph', $q);
        $this->db->or_like('total_pph', $q);
        $this->db->or_like('unix', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('created_at', $q);
        $this->db->or_like('updated_at', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    public function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    public function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    public function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Asal_pemilik_model.php */
/* Location: ./application/models/Asal_pemilik_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-24 11:40:37 */
/* http://harviacode.com */
