<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Permohonan_model extends CI_Model
{
    public $table = 'permohonan';
    public $id = 'id';
    public $order = 'DESC';

    public function __construct()
    {
        parent::__construct();
    }

    // get all
    public function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    public function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    public function total_rows($q = null)
    {
        $this->db->like('id', $q);
        $this->db->or_like('parent', $q);
        $this->db->or_like('operasional', $q);
        $this->db->or_like('no_rkbm', $q);
        $this->db->or_like('mulai', $q);
        $this->db->or_like('selesai', $q);
        $this->db->or_like('kapal', $q);
        $this->db->or_like('tempat_muat', $q);
        $this->db->or_like('barang', $q);
        $this->db->or_like('tempat_bongkar', $q);
        $this->db->or_like('jumlah_muatan', $q);
        $this->db->or_like('jumlah_asli', $q);
        $this->db->or_like('jumlah_bongkar', $q);
        $this->db->or_like('asal_barang', $q);
        $this->db->or_like('perusahaan', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('permohonan_jenis', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    public function get_limit_data($limit, $start = 0, $q = null)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('parent', $q);
        $this->db->or_like('operasional', $q);
        $this->db->or_like('no_rkbm', $q);
        $this->db->or_like('mulai', $q);
        $this->db->or_like('selesai', $q);
        $this->db->or_like('kapal', $q);
        $this->db->or_like('tempat_muat', $q);
        $this->db->or_like('barang', $q);
        $this->db->or_like('tempat_bongkar', $q);
        $this->db->or_like('jumlah_muatan', $q);
        $this->db->or_like('jumlah_asli', $q);
        $this->db->or_like('jumlah_bongkar', $q);
        $this->db->or_like('asal_barang', $q);
        $this->db->or_like('perusahaan', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('permohonan_jenis', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    public function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    public function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    public function delete($id)
    {
        
			if ( ! $this->db->delete('permohonan', array('id' => $id)))
            {
                
                            $error = $this->db->error();
                            // var_dump($error);
            if ($error['code'] == 1451) {
                return  'foreign_key';
            }
                            return $error;
            }
        // $this->db->where($this->id, $id);
        // $hapus = $this->db->delete($this->table);
        // // var_dump($hapus);
        // if ($hapus) {
        //     return true;
        // } else {
        //     if ($this->db->_error_number() == 1451) {
        //         echo  'foreign_key';
        //     }
        // }
    }
}

/* End of file Permohonan_model.php */
/* Location: ./application/models/Permohonan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-03 10:40:27 */
/* http://harviacode.com */
