<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Rkbm_model extends CI_Model
{

    public $table = 'rkbm';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('no_surat_rkbm', $q);
	$this->db->or_like('exp_id', $q);
	$this->db->or_like('no_rkbm', $q);
	$this->db->or_like('no_invoice', $q);
	$this->db->or_like('nama_kapal', $q);
	$this->db->or_like('bendera', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('agen', $q);
	$this->db->or_like('bongkar', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('jumlah_real', $q);
	$this->db->or_like('mulai', $q);
	$this->db->or_like('selesai', $q);
	$this->db->or_like('buruh', $q);
	$this->db->or_like('asal_brg', $q);
	$this->db->or_like('pemilik_brg', $q);
	$this->db->or_like('tujuan', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('loading', $q);
	$this->db->or_like('loading_detail', $q);
	$this->db->or_like('operasional', $q);
	$this->db->or_like('biaya_operasional', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('tanggal_invoice', $q);
	$this->db->or_like('tanggal_exp_invoice', $q);
	$this->db->or_like('tanggal_final', $q);
	$this->db->or_like('perusahaan', $q);
	$this->db->or_like('admin_by', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('no_surat_rkbm', $q);
	$this->db->or_like('exp_id', $q);
	$this->db->or_like('no_rkbm', $q);
	$this->db->or_like('no_invoice', $q);
	$this->db->or_like('nama_kapal', $q);
	$this->db->or_like('bendera', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('agen', $q);
	$this->db->or_like('bongkar', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('jumlah_real', $q);
	$this->db->or_like('mulai', $q);
	$this->db->or_like('selesai', $q);
	$this->db->or_like('buruh', $q);
	$this->db->or_like('asal_brg', $q);
	$this->db->or_like('pemilik_brg', $q);
	$this->db->or_like('tujuan', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('loading', $q);
	$this->db->or_like('loading_detail', $q);
	$this->db->or_like('operasional', $q);
	$this->db->or_like('biaya_operasional', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('tanggal_invoice', $q);
	$this->db->or_like('tanggal_exp_invoice', $q);
	$this->db->or_like('tanggal_final', $q);
	$this->db->or_like('perusahaan', $q);
	$this->db->or_like('admin_by', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Rkbm_model.php */
/* Location: ./application/models/Rkbm_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-24 11:40:37 */
/* http://harviacode.com */