<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Semua_model extends CI_Model
{

    public $table = 'rkbm';
    public $id    = 'id';
    public $order = 'DESC';

    public function __construct()
    {
        parent::__construct();
    }

    // get all
    public function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($table)->result();
    }

    // get data by id
    public function get_by_id($table, $id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($table)->row();
    }

    // insert data
    public function insert($table, $data)
    {
        $this->db->insert($table, $data);
    }

    // update data
    public function update($table, $id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($table, $data);
    }

    // delete data
    public function delete($table, $id)
    {
        $this->db->where('id', $id);
        $this->db->delete($table);
    }

}

/* End of file Rkbm_model.php */
/* Location: ./application/models/Rkbm_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-02-24 11:40:37 */
/* http://harviacode.com */